const { ACCOUNT_TYPES } = require("./auth");

const MACHINE_CONTROL_ACTOR_TYPES = Object.freeze({
  BACKOFFICE: ACCOUNT_TYPES.BACKOFFICE,
  OWNER: ACCOUNT_TYPES.OWNER,
  KASIR: ACCOUNT_TYPES.KASIR,
});

module.exports = { MACHINE_CONTROL_ACTOR_TYPES };
