CREATE TABLE tbl_mitra (
    id INT AUTO_INCREMENT PRIMARY KEY,
    kodeMitra VARCHAR(50) NOT NULL UNIQUE,
    namaMitra VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL,
    createdDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    createdBy VARCHAR(100) NOT NULL
);
